### PR TITLE
Added triple buffering to DRM backend

### PR DESCRIPTION
**Pull request by oomek**
Fixes the performance degradation during page flipping when compared to Dispmanx backend which by default has triple buffering enabled.

### CODE REVIEW

**Comment by joyrider3774** [comment]
Hey i tested this this increases performance considerably under drm. FPS is a lot higher compared to original code. Probably because attract / sfml-pi can draw already on the next surface. Good work @oomek

**Comment by joyrider3774** [comment]
it seems but we are still investigating that there might be problem with this pr when returning from emulators that the screen is not recreated i would not merge yet until fully investigated. The orginal double buffer version (master) does not seem to exhibit this problem

**Comment by oomek** [comment]
Added missing cleanup calls.

**Comment by joyrider3774** [comment]
the missing cleanup calls seems to have fixed the problem with the screen not being recreated after returning from emus. works fine now as far as i can tell and is faster inside attract

**Comment by calle81** [comment]
I can confirm that this greatly improves the fps on the RPi4. Thanks Oomek!

**Comment by mickelson** [comment]
works great here, thanks Oomek!

**Pull request merged**
