### PR TITLE
Update to SFML 2.5.1

### PR DESCRIPTION
**Pull request by oomek**

### CODE REVIEW

**Comment by calle81** [comment]
I've been testing this update using Oomeks repository on my RPi4 and it works perfectly. Previously there were some minor issues with Attract Mode on RPi4 with lockups etc but with these latest updates it's flawless on Retropie. Will you merge this Andrew so we can ask everyone having issues to update?

**Comment by oomek** [comment]
The lockups were actually fixed by Andrew with a little help from my side. The 2.5.1 update addresses visual glitches like like faint borders around letters and images.

**Comment by calle81** [comment]
Ah, ok! Well it looks as good as it does on my PC now using the HyperPie themes so good work :)

**Comment by mickelson** [comment]
Thanks for the update!

**Pull request merged**
