### PR TITLE
support multitouch on Raspberry Pi

### PR DESCRIPTION
**Pull request by ppelleti**
I have the [Raspberry Pi Touch Display](https://www.raspberrypi.org/products/raspberry-pi-touch-display/), and I'd like to use sfml-pi with it.  So, I've added support for touch events on Raspberry Pi.

### CODE REVIEW

**Comment by mickelson** [comment]
i hope to have a chance to look at this soon.  thanks

**Comment by ppelleti** [comment]
Thanks!  The way I interact with the event queue is a bit sketchy, but I couldn't think of a better way to do it.  Perhaps you'll have an idea for how to make it cleaner.

**Comment by ppelleti** [comment]
BTW, the documentation for Linux multi-touch is at https://www.kernel.org/doc/Documentation/input/multi-touch-protocol.txt

**Comment by mickelson** [comment]
better late than never!

**Pull request merged**
